name: CI-Alpha-Xamarin-Nuget

on:
  pull_request:
    branches: [ alpha ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate version
        id: generate_version
        run: |
          DATE=$(date +'%Y.%m.%d')
          BUILD_NUMBER=$(git rev-list --count HEAD)
          VERSION="$DATE.$BUILD_NUMBER"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Print version
        run: echo "${{ env.VERSION }}"
