name: CI-Development
on:
  pull_request:
    branches:
      - development
jobs:
  publish:
    name: dev
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Xamarin iOS project
        run: MSBuild /p:Configuration=Release Omnicasa.Mobile.BlinkID.iOS/Omnicasa.Mobile.BlinkID.iOS.csproj

      - name: Install .NET tools
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.400
          
      - name: Install .NET MAUI
        run: dotnet workload install maui
        
      - name: Build Maui iOS project
        run: dotnet build -c Release Omnicasa.Mobile.BlinkID.Maui.iOS/Omnicasa.Mobile.BlinkID.Maui.iOS.csproj
