name: NugetPublish
on:
  push:
    branches:
      - master3
jobs:
  publish:
    name: build, pack & publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: iOS Generating project version
        uses: EduardSergeev/project-version-action@v6
        with:
            version-file: Omnicasa.Mobile.Maui.BlinkID.iOS/Omnicasa.Mobile.Maui.BlinkID.iOS.csproj
            version-stub: '65534.65534.65534.65534'

      - name: Droid Generating project version
        uses: EduardSergeev/project-version-action@v6
        with:
            version-file: Omnicasa.Mobile.Maui.BlinkID.Droid/Omnicasa.Mobile.Maui.BlinkID.Droid.csproj
            version-stub: '65534.65534.65534.65534'    

      - name: iOS Set version for project
        id: updateiOS
        uses: vers-one/dotnet-project-version-updater@v1.3
        with:
          file: "Omnicasa.Mobile.Maui.BlinkID.iOS/Omnicasa.Mobile.Maui.BlinkID.iOS.csproj"
          version: ${{ env.VERSION }}

      - name: Droid Set version for project
        id: updateDroid
        uses: vers-one/dotnet-project-version-updater@v1.3
        with:
          file: "Omnicasa.Mobile.Maui.BlinkID.Droid/Omnicasa.Mobile.Maui.BlinkID.Droid.csproj"
          version: ${{ env.VERSION }}

      - name: Install .NET MAUI
        run: dotnet workload install maui   
         
      # Publish
      - name: iOS Publish on version change
        id: publish_nuget_iOS
        uses: linch90/publish-nuget@v1.0.2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Omnicasa.Mobile.Maui.BlinkID.iOS/Omnicasa.Mobile.Maui.BlinkID.iOS.csproj

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          NUGET_SOURCE: https://api.nuget.org

          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          VERSION_STATIC: ${{env.VERSION}}

      - name: Droid Publish on version change
        id: publish_nuget_Droid
        uses: linch90/publish-nuget@v1.0.2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Omnicasa.Mobile.Maui.BlinkID.Droid/Omnicasa.Mobile.Maui.BlinkID.Droid.csproj

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          NUGET_SOURCE: https://api.nuget.org

          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          VERSION_STATIC: ${{env.VERSION}}